    <!-- Mobile viewport optimisation -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  	
    <!-- JavaScript Detection -->
    <script>document.documentElement.className += " js";</script>
  	
    <link href="{{ page.baseptr }}/css/central.css" rel="stylesheet" type="text/css"/>
    
    <!--[if lte IE 7]>
      <link href="{{ page.baseptr }}/yaml/core/iehacks.min.css" rel="stylesheet" type="text/css" />
    <![endif]-->
