{% if page.prjpypi %}
New versions of the code are be published for download 
at [PyPI - the Python Package Index](http://pypi.python.org/pypi/{{ page.prjname }}) 
periodically.
{% endif %}

You can download the latest development version of this code that is hosted 
in [GitHub](https://github.com/{{ site.user }}/{{ page.prjname }}) either
in [zip](https://github.com/{{ site.user }}/{{ page.prjname }}/zipball/master)
or [tar](https://github.com/{{ site.user }}/{{ page.prjname }}/tarball/master).

You can also get the latest development version of the code by cloning  
the [Git](http://git-scm.com) repository for the project by running:

<pre>
git clone git://github.com/{{ site.user }}/{{ page.prjname }}
</pre>
